### ISSUE TITLE
Get LinkedIn user full profile + Logout from LinkedIn

### ISSUE THREAD

**Issue by AndreiBoariu** [serhii-londar/LinkedInSignIn#3]
Really appreciate for your hard work with this great library!

Is there a way to get full profile of logged in user based on token?
I think that can be done easily during completion. Its just a suggestion 👍 

Is there a possibility to logout user ?
I have this case:
1) enter credentials
2) get user token
3) get full profile by calling another API
4) join in app(my app)
5) logout from my app, and again login with LinkedIn
At this point its automatically fetch token for credentials added first time, and no way to enter other credentials only if I delete the app from device.
I think there should be a logout function just to remove initial data.

Thanks!

**Comment by serhii-londar** [comment]
Hi @AndreiBoariu! Thanks for your feedback! I've just added the logout functionality. You can check it in new release [v 0.1.3](https://github.com/serhii-londar/LinkedInSignIn/releases/tag/0.1.3). It will be available via cocoa pods shortly.

**Comment by AndreiBoariu** [comment]
@serhii-londar Really appreciate.
Let us know when update will be ready via cp. Thanks

**Comment by serhii-londar** [comment]
@AndreiBoariu Should be available. Just uploaded.
